apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-sample
  namespace: default
spec:
  releaseName: capi01
  chart:
    git: https://github.com/danielsollondon/clusterdemo
    ref: main
    path: charts/clusterConfig
